[package]
name = "advent2019"
version = "0.1.0"
authors = ["Mike Mueller <mike@subfocal.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argparse = ""
lazy_static = ""
num = ""
num-derive = ""
num-integer = ""
num-traits = ""
permutohedron = ""
regex = ""
