// GENERATED BY build.rs
// DO NOT EDIT BY HAND, CHANGES WILL BE LOST.
use anyhow::format_err;
pub mod day01;

// Execute the solution for a particular day (1..25).
pub fn solve(day: usize) -> Result<(), anyhow::Error> {
    let mut solver: Box<dyn AdventSolver> = match day {
         1 => Box::new(day01::Solver::default()),
         _ => { return Err(format_err!("Invalid day number: {}", day)); }
    };
    solver.solve()
}
